domain: 'mlfurs.org'
from: 'mlfurs'
contact: 'listmaster@mlfurs.org'
title: 'MLFurs.org'
mailman_dir: '/usr/local/mailman/'
aes_key: '108b24a4b269d19eee75999c7cd6a4598f9c90dd'
locale: 'fr'
lists: ["paris", "marseille", "belgique"]
